spring:
  application:
    name: service-demo

server:
  port: 8077
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/


