spring:
  application:
    name: service-demo

server:
  port: 8078
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/


