spring:
  application:
    name: consumer-demo


server:
  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/